/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSimuladorCdbRouteImport } from './routes/_app.simulador-cdb'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppRebalanceamentoRouteImport } from './routes/_app.rebalanceamento'
import { Route as AppOutrosBensRouteImport } from './routes/_app.outros-bens'
import { Route as AppJurosCompostosRouteImport } from './routes/_app.juros-compostos'
import { Route as AppEstatisticasRouteImport } from './routes/_app.estatisticas'
import { Route as AppCarteirasPortfolioIdRouteImport } from './routes/_app.carteiras.$portfolioId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSimuladorCdbRoute = AppSimuladorCdbRouteImport.update({
  id: '/simulador-cdb',
  path: '/simulador-cdb',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppRebalanceamentoRoute = AppRebalanceamentoRouteImport.update({
  id: '/rebalanceamento',
  path: '/rebalanceamento',
  getParentRoute: () => AppRoute,
} as any)
const AppOutrosBensRoute = AppOutrosBensRouteImport.update({
  id: '/outros-bens',
  path: '/outros-bens',
  getParentRoute: () => AppRoute,
} as any)
const AppJurosCompostosRoute = AppJurosCompostosRouteImport.update({
  id: '/juros-compostos',
  path: '/juros-compostos',
  getParentRoute: () => AppRoute,
} as any)
const AppEstatisticasRoute = AppEstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => AppRoute,
} as any)
const AppCarteirasPortfolioIdRoute = AppCarteirasPortfolioIdRouteImport.update({
  id: '/carteiras/$portfolioId',
  path: '/carteiras/$portfolioId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/estatisticas': typeof AppEstatisticasRoute
  '/juros-compostos': typeof AppJurosCompostosRoute
  '/outros-bens': typeof AppOutrosBensRoute
  '/rebalanceamento': typeof AppRebalanceamentoRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/simulador-cdb': typeof AppSimuladorCdbRoute
  '/carteiras/$portfolioId': typeof AppCarteirasPortfolioIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/estatisticas': typeof AppEstatisticasRoute
  '/juros-compostos': typeof AppJurosCompostosRoute
  '/outros-bens': typeof AppOutrosBensRoute
  '/rebalanceamento': typeof AppRebalanceamentoRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/simulador-cdb': typeof AppSimuladorCdbRoute
  '/': typeof AppIndexRoute
  '/carteiras/$portfolioId': typeof AppCarteirasPortfolioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/estatisticas': typeof AppEstatisticasRoute
  '/_app/juros-compostos': typeof AppJurosCompostosRoute
  '/_app/outros-bens': typeof AppOutrosBensRoute
  '/_app/rebalanceamento': typeof AppRebalanceamentoRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/simulador-cdb': typeof AppSimuladorCdbRoute
  '/_app/': typeof AppIndexRoute
  '/_app/carteiras/$portfolioId': typeof AppCarteirasPortfolioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/estatisticas'
    | '/juros-compostos'
    | '/outros-bens'
    | '/rebalanceamento'
    | '/relatorios'
    | '/simulador-cdb'
    | '/carteiras/$portfolioId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/estatisticas'
    | '/juros-compostos'
    | '/outros-bens'
    | '/rebalanceamento'
    | '/relatorios'
    | '/simulador-cdb'
    | '/'
    | '/carteiras/$portfolioId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/estatisticas'
    | '/_app/juros-compostos'
    | '/_app/outros-bens'
    | '/_app/rebalanceamento'
    | '/_app/relatorios'
    | '/_app/simulador-cdb'
    | '/_app/'
    | '/_app/carteiras/$portfolioId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/simulador-cdb': {
      id: '/_app/simulador-cdb'
      path: '/simulador-cdb'
      fullPath: '/simulador-cdb'
      preLoaderRoute: typeof AppSimuladorCdbRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rebalanceamento': {
      id: '/_app/rebalanceamento'
      path: '/rebalanceamento'
      fullPath: '/rebalanceamento'
      preLoaderRoute: typeof AppRebalanceamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outros-bens': {
      id: '/_app/outros-bens'
      path: '/outros-bens'
      fullPath: '/outros-bens'
      preLoaderRoute: typeof AppOutrosBensRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/juros-compostos': {
      id: '/_app/juros-compostos'
      path: '/juros-compostos'
      fullPath: '/juros-compostos'
      preLoaderRoute: typeof AppJurosCompostosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estatisticas': {
      id: '/_app/estatisticas'
      path: '/estatisticas'
      fullPath: '/estatisticas'
      preLoaderRoute: typeof AppEstatisticasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carteiras/$portfolioId': {
      id: '/_app/carteiras/$portfolioId'
      path: '/carteiras/$portfolioId'
      fullPath: '/carteiras/$portfolioId'
      preLoaderRoute: typeof AppCarteirasPortfolioIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppEstatisticasRoute: typeof AppEstatisticasRoute
  AppJurosCompostosRoute: typeof AppJurosCompostosRoute
  AppOutrosBensRoute: typeof AppOutrosBensRoute
  AppRebalanceamentoRoute: typeof AppRebalanceamentoRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppSimuladorCdbRoute: typeof AppSimuladorCdbRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCarteirasPortfolioIdRoute: typeof AppCarteirasPortfolioIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEstatisticasRoute: AppEstatisticasRoute,
  AppJurosCompostosRoute: AppJurosCompostosRoute,
  AppOutrosBensRoute: AppOutrosBensRoute,
  AppRebalanceamentoRoute: AppRebalanceamentoRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppSimuladorCdbRoute: AppSimuladorCdbRoute,
  AppIndexRoute: AppIndexRoute,
  AppCarteirasPortfolioIdRoute: AppCarteirasPortfolioIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
